import { auth, db, firebaseConfig, customerEmailFromLogin } from "./firebase.js";
import { signInWithEmailAndPassword,onAuthStateChanged,signOut,createUserWithEmailAndPassword,getAuth,getIdTokenResult } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,where,serverTimestamp,runTransaction,onSnapshot } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const $=s=>document.querySelector(s),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
let medicines=[],customers=[],orders=[],blacklistRequests=[],unsubscribeOrders=null;const customerApp=initializeApp(firebaseConfig,"zeno-customer-creator-v2"),customerAuth=getAuth(customerApp);
function notify(msg){$("#toast").textContent=msg;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2600);if("Notification"in window&&Notification.permission==="granted")new Notification("ZenoLife Care",{body:msg})}
async function requestNotifications(){if("Notification"in window&&Notification.permission==="default")try{await Notification.requestPermission()}catch{}}
if($("#adminLoginForm"))$("#adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();$("#adminLoginMsg").textContent="Signing in…";try{const cred=await signInWithEmailAndPassword(auth,$("#adminEmail").value.trim(),$("#adminPassword").value);const token=await getIdTokenResult(cred.user,true);if(token.claims.admin!==true){await signOut(auth);$("#adminLoginMsg").textContent="⚠ This is an Admin page. Only authorized Admin accounts can login here.";return}location.replace("admin-dashboard.html")}catch{$("#adminLoginMsg").textContent="⚠ This is an Admin page. Only authorized Admin accounts can login here, or the credentials are incorrect."}});
onAuthStateChanged(auth,async user=>{if(!user){if(location.pathname.endsWith("admin-dashboard.html"))location.replace("admin.html");return}if(location.pathname.endsWith("admin.html")){location.replace("admin-dashboard.html");return}try{const t=await getIdTokenResult(user,true);if(t.claims.admin!==true)throw 0;if($("#adminApp")){await requestNotifications();await loadAll();watchOrders();restoreTab()}}catch{await signOut(auth);location.replace("admin.html")}});
async function loadAll(){await Promise.all([loadMedicines(),loadCustomers(),loadOrders(),loadBlacklistRequests()]);stats()}
async function loadMedicines(){const s=await getDocs(collection(db,"medicines")),p=await getDocs(collection(db,"medicinePrivate")),pm=new Map(p.docs.map(d=>[d.id,d.data()]));medicines=s.docs.map(d=>({id:d.id,...d.data(),...(pm.get(d.id)||{})}));renderMedicines()}
async function loadCustomers(){const s=await getDocs(collection(db,"customers"));customers=s.docs.map(d=>({id:d.id,...d.data()}));renderCustomers()}
async function loadBlacklistRequests(){try{const s=await getDocs(collection(db,"blacklistRequests"));blacklistRequests=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));renderBlacklistRequests()}catch{blacklistRequests=[];renderBlacklistRequests()}}
async function loadOrders(){const s=await getDocs(collection(db,"orders"));orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.orderTimeMs||0)-(a.orderTimeMs||0));renderOrders();stats()}
function watchOrders(){if(unsubscribeOrders)unsubscribeOrders();unsubscribeOrders=onSnapshot(query(collection(db,"orders")),snap=>{const prev=new Set(orders.map(o=>o.id));orders=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.orderTimeMs||0)-(a.orderTimeMs||0));const fresh=orders.filter(o=>!prev.has(o.id)&&o.status==="new");if(fresh.length)notify(`New order received • ${fresh[0].medicalName||fresh[0].customerName||"Customer"} • ${fresh[0].billId||"Bill"}`);renderOrders();stats()})}
function itemProfit(x){const m=medicines.find(v=>v.id===x.medicineId)||{};const rate=Number(x.rate||0),purchase=Number(x.purchaseRateAtOrder??m.purchaseRate??0),qty=Number(x.qty||0),gst=Number(m.gst||x.gstAtOrder||0),transport=Number(m.transport??x.transportAtOrder??0);const effectivePurchase=(purchase+gst+transport)*qty;return (rate*qty)-effectivePurchase}
function orderProfit(o){return (o.items||[]).reduce((sum,x)=>sum+itemProfit(x),0)}
function stats(){const low=medicines.filter(m=>Number(m.quantity)<=10),exp=medicines.filter(m=>{if(!m.expiry)return false;const d=new Date(m.expiry),n=new Date();return d>=new Date(n.getFullYear(),n.getMonth(),n.getDate())&&d<=new Date(n.getFullYear(),n.getMonth(),n.getDate()+30)}),profit=orders.filter(o=>o.status!=="cancelled").reduce((s,o)=>s+orderProfit(o),0);$("#statMedicines").textContent=medicines.length;$("#statCustomers").textContent=customers.length;$("#statOrders").textContent=orders.filter(o=>o.status==="new").length;$("#statLow").textContent=low.length;$("#statExpiry").textContent=exp.length;$("#statProfit").textContent=money(profit);$("#alertPanel").innerHTML=(low.length||exp.length)?`<div class="alert-box">${low.length?`⚠️ ${low.length} low-stock medicine(s).`:""} ${exp.length?`⏳ ${exp.length} medicine(s) expiring within 30 days.`:""}</div>`:`<div class="alert-box success-alert">✓ Inventory looks healthy.</div>`}
function renderMedicines(){const term=($("#adminMedicineSearch")?.value||"").toLowerCase().trim(),list=medicines.filter(m=>(m.name||"").toLowerCase().includes(term)||(m.composition||"").toLowerCase().includes(term)||(m.category||"").toLowerCase().includes(term));$("#adminMedicineTable").innerHTML=`<div class="table-scroll"><table><thead><tr><th>Image</th><th>Drug</th><th>Qty</th><th>Expiry</th><th>MRP</th><th>N. Rate</th><th>Purchase</th><th>GST</th><th>Transport</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${list.map(m=>`<tr><td>${m.imageData?`<img class="table-thumb" src="${esc(m.imageData)}">`:"—"}</td><td><b>${esc(m.name)}</b><small>${esc(m.composition||"")}</small></td><td>${m.quantity}</td><td>${esc(m.expiry||"—")}</td><td>${money(m.mrp)}</td><td>${money(m.sellRate)}</td><td>${money(m.purchaseRate)}</td><td>${money(m.gst)}</td><td>${money(m.transport)}</td><td><button class="stock-toggle ${m.available?"yes":"no"}" data-stock="${m.id}">${m.available?"ON":"OFF"}</button></td><td><button class="mini" data-edit="${m.id}">Edit</button><button class="mini danger" data-del="${m.id}">Delete</button></td></tr>`).join("")}</tbody></table></div>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openMedicine(medicines.find(m=>m.id===b.dataset.edit)));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>deleteMedicine(b.dataset.del));document.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>toggleStock(b.dataset.stock))}
function renderBlacklistRequests(){const box=$("#blacklistRequests");if(!box)return;const pending=blacklistRequests.filter(r=>r.status==="pending");box.innerHTML=pending.length?pending.map(r=>{const c=customers.find(x=>x.id===r.customerId);return `<div class="request-card glass"><div><b>${esc(c?.medicalName||r.loginId||"Customer")}</b><small>${esc(c?.name||"")} • ${esc(c?.phone||r.loginId||"")}</small></div><button class="mini primary" data-unblack-request="${r.id}" data-request-customer="${r.customerId}">Unblacklist & Approve</button></div>`}).join(""):"<div class='empty'>No pending blacklist requests.</div>";document.querySelectorAll("[data-unblack-request]").forEach(b=>b.onclick=()=>approveBlacklistRequest(b.dataset.unblackRequest,b.dataset.requestCustomer))}
async function approveBlacklistRequest(requestId,customerId){try{await updateDoc(doc(db,"customers",customerId),{active:true,updatedAt:serverTimestamp()});await updateDoc(doc(db,"blacklistRequests",requestId),{status:"approved",handledAt:serverTimestamp()});await Promise.all([loadCustomers(),loadBlacklistRequests()]);notify("Customer unblacklisted ✓")}catch(e){notify(e.message||"Could not approve request")}}
function renderCustomers(){const list=customers;$("#customerTable").innerHTML=`<div class="table-scroll"><table><thead><tr><th>Medical</th><th>Owner/Name</th><th>Phone</th><th>Address</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map(c=>`<tr class="${c.active===false?"blacklisted-row":""}"><td><b>${esc(c.medicalName||"")}</b><small>${esc(c.loginId||"")}</small></td><td>${esc(c.name||"")}</td><td>${esc(c.phone||"")}</td><td>${esc(c.address||"—")}</td><td>${c.active===false?`<span class="blacklisted-badge">⚠ BLACKLISTED</span>`:`<span class="status confirmed">Active</span>`}</td><td><button class="mini" data-cview="${c.id}">Details</button><button class="mini ${c.active===false?"primary":"danger"}" data-black="${c.id}">${c.active===false?"Unblacklist":"Blacklist"}</button></td></tr>`).join("")}</tbody></table></div>`;document.querySelectorAll("[data-black]").forEach(b=>b.onclick=()=>toggleCustomer(b.dataset.black));renderBlacklistRequests()}
function groupOrders(){const map=new Map();orders.forEach(o=>{const d=new Date(o.orderTimeMs||Date.now()).toLocaleDateString("en-IN");const key=d+"|"+(o.medicalName||o.customerName||"Customer");if(!map.has(key))map.set(key,{date:d,medical:o.medicalName||o.customerName||"Customer",orders:[]});map.get(key).orders.push(o)});return [...map.values()]}
function renderOrders(){const groups=groupOrders();$("#orderTable").innerHTML=groups.length?groups.map(g=>`<section class="order-day"><div class="day-head"><div><div class="eyebrow">${esc(g.date)}</div><h3>${esc(g.medical)}</h3></div><span>${g.orders.length} bill(s)</span></div>${g.orders.map(o=>`<article class="admin-order glass"><div><b>Bill ${esc(o.billId||o.id.slice(-6).toUpperCase())}</b><small>${new Date(o.orderTimeMs||Date.now()).toLocaleTimeString("en-IN")} • ${o.items?.length||0} products</small></div><strong>${money(o.total)}</strong><span class="status ${esc(o.status)}">${esc(o.status)}</span><button class="ghost" data-bill="${o.id}">Details</button><select data-status="${o.id}"><option value="new" ${o.status==="new"?"selected":""}>New</option><option value="confirmed" ${o.status==="confirmed"?"selected":""}>Confirm</option><option value="completed" ${o.status==="completed"?"selected":""}>Completed</option><option value="cancelled" ${o.status==="cancelled"?"selected":""}>Cancel</option></select></article>`).join("")}</section>`).join(""):"<div class='empty glass'>No orders yet.</div>";document.querySelectorAll("[data-bill]").forEach(b=>b.onclick=()=>openAdminBill(orders.find(o=>o.id===b.dataset.bill)));document.querySelectorAll("[data-status]").forEach(s=>s.onchange=()=>updateStatus(s.dataset.status,s.value))}
function billHtml(o){const totalProfit=orderProfit(o);return `<div class="bill"><div class="bill-head"><div><b>ZenoLife Care</b><small>Retailer Bill • Admin View</small></div><strong>${esc(o.billId||"")}</strong></div><div class="bill-customer"><b>${esc(o.medicalName||"")}</b><span>${esc(o.customerName||"")} • ${esc(o.phone||"")}</span>${o.address?`<span>${esc(o.address)}</span>`:""}</div><div class="bill-items">${(o.items||[]).map((x,i)=>{const m=medicines.find(v=>v.id===x.medicineId)||{};const purchase=Number(x.purchaseRateAtOrder??m.purchaseRate??0),gst=Number(m.gst??x.gstAtOrder??0),transport=Number(m.transport??x.transportAtOrder??0),profit=itemProfit(x);return `<div class="bill-line"><span>${i+1}. ${esc(x.name)} × ${x.qty}</span><span>N. Rate ${money(x.rate)} • Purchase ${money(purchase)} • GST ${money(gst)} • Transport ${money(transport)} • Profit ${money(profit)}</span></div>`}).join("")}</div><div class="bill-total"><span>Customer Total</span><b>${money(o.total)}</b></div><div class="admin-profit-box">Admin Profit <small>(N. Rate − (Purchase + GST + Transport))</small>: <b>${money(totalProfit)}</b></div><small>${new Date(o.orderTimeMs||Date.now()).toLocaleString("en-IN")} • ${esc(o.status)}</small></div>`}
function openAdminBill(o){if(!o)return;$("#adminBillContent").innerHTML=billHtml(o);$("#adminBillDialog").showModal()}
async function updateStatus(id,status){try{const ref=doc(db,"orders",id);if(status==="completed"){await runTransaction(db,async tx=>{const os=await tx.get(ref);if(!os.exists())throw Error("Order not found");const o=os.data();if(o.status!=="completed"){for(const x of o.items||[]){const mr=doc(db,"medicines",x.medicineId),ms=await tx.get(mr);if(ms.exists()){const n=Math.max(0,Number(ms.data().quantity||0)-Number(x.qty||0));tx.update(mr,{quantity:n,available:n>0,updatedAt:serverTimestamp()})}}}tx.update(ref,{status,updatedAt:serverTimestamp()})})}else await updateDoc(ref,{status,updatedAt:serverTimestamp()});await loadAll();notify(`Bill ${id.slice(-6).toUpperCase()} marked ${status}`)}catch(e){notify(e.message||"Status update failed")}}
async function toggleCustomer(id){const c=customers.find(x=>x.id===id);if(!c)return;const blacklist=c.active!==false;if(blacklist&&!confirm(`Blacklist ${c.medicalName||c.name}?`))return;await updateDoc(doc(db,"customers",id),{active:!blacklist,updatedAt:serverTimestamp()});renderCustomers();notify(blacklist?"Customer blacklisted ⚠":"Customer unblacklisted ✓")}
$("#customerForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const medicalName=$("#cMedical").value.trim(),name=$("#cName").value.trim(),phone=$("#cPhone").value.trim(),address=$("#cAddress").value.trim(),loginId=$("#cLogin").value.trim().toLowerCase(),password=$("#cPassword").value;if(!medicalName||!name||!phone||!address||!loginId||password.length<6)throw Error("Please fill all customer details.");const cred=await createUserWithEmailAndPassword(customerAuth,customerEmailFromLogin(loginId),password);await setDoc(doc(db,"customers",cred.user.uid),{medicalName,name,phone,address,loginId,active:true,createdAt:serverTimestamp()});await signOut(customerAuth);$("#customerDialog").close();await loadCustomers();stats();notify("Customer created ✓")}catch(e){try{await signOut(customerAuth)}catch{}$("#customerMsg").textContent=e.message||"Customer creation failed."}});
$("#medicineForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const id=$("#medicineId").value,imageFile=$("#mImage").files[0],data={name:$("#mName").value.trim(),category:$("#mCategory").value.trim(),composition:$("#mComposition").value.trim(),quantity:Number($("#mQty").value),expiry:$("#mExp").value,mrp:Number($("#mMrp").value),sellRate:Number($("#mSell").value),available:$("#mAvailable").checked,updatedAt:serverTimestamp()};if(imageFile)data.imageData=await compressImage(imageFile);let mid=id;if(mid)await updateDoc(doc(db,"medicines",mid),data);else mid=(await addDoc(collection(db,"medicines"),{...data,createdAt:serverTimestamp()})).id;await setDoc(doc(db,"medicinePrivate",mid),{purchaseRate:Number($("#mPurchase").value),gst:Number($("#mGst").value),transport:Number($("#mTransport").value),updatedAt:serverTimestamp()},{merge:true});$("#medicineDialog").close();await loadMedicines();stats();notify("Medicine saved ✓")}catch(e){$("#medicineMsg").textContent=e.message||"Save failed."}});
function openMedicine(m){$("#medicineForm").reset();$("#medicineId").value=m?.id||"";$("#medicineDialogTitle").textContent=m?"Edit Medicine":"Add Medicine";if(m){$("#mName").value=m.name||"";$("#mCategory").value=m.category||"";$("#mComposition").value=m.composition||"";$("#mQty").value=m.quantity??0;$("#mExp").value=m.expiry||"";$("#mMrp").value=m.mrp??0;$("#mSell").value=m.sellRate??0;$("#mPurchase").value=m.purchaseRate??0;$("#mGst").value=m.gst??0;$("#mTransport").value=m.transport??0;$("#mAvailable").checked=m.available!==false}$("#medicineDialog").showModal()}
async function deleteMedicine(id){if(!confirm("Delete this medicine?"))return;await deleteDoc(doc(db,"medicines",id));await deleteDoc(doc(db,"medicinePrivate",id));await loadMedicines();stats();notify("Medicine deleted")}
async function toggleStock(id){const m=medicines.find(x=>x.id===id);await updateDoc(doc(db,"medicines",id),{available:!m.available,updatedAt:serverTimestamp()});await loadMedicines()}
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const i=new Image();i.onload=()=>{const c=document.createElement("canvas"),s=Math.min(1,600/Math.max(i.width,i.height));c.width=i.width*s;c.height=i.height*s;c.getContext("2d").drawImage(i,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.68))};i.onerror=reject;i.src=r.result};r.readAsDataURL(file)})}
$("#adminMedicineSearch")?.addEventListener("input",renderMedicines);$("#clearAdminSearch")?.addEventListener("click",()=>{$("#adminMedicineSearch").value="";renderMedicines()});$("#addMedicineBtn")?.addEventListener("click",()=>openMedicine());$("#closeMedicine")?.addEventListener("click",()=>$("#medicineDialog").close());$("#addCustomerBtn")?.addEventListener("click",()=>{$("#customerForm").reset();$("#customerDialog").showModal()});$("#closeCustomer")?.addEventListener("click",()=>$("#customerDialog").close());$("#adminLogout")?.addEventListener("click",async()=>{await signOut(auth);location.replace("admin.html")});$("#supportBtn")?.addEventListener("click",()=>$("#supportDialog").showModal());$("#closeSupport")?.addEventListener("click",()=>$("#supportDialog").close());$("#closeAdminBill")?.addEventListener("click",()=>$("#adminBillDialog").close());$("#menuBtn")?.addEventListener("click",()=>$("#sideMenu").classList.add("open"));$("#closeMenu")?.addEventListener("click",()=>$("#sideMenu").classList.remove("open"));document.querySelectorAll("[data-menu-tab]").forEach(b=>b.onclick=()=>{const t=document.querySelector(`.tab[data-tab="${b.dataset.menuTab}"]`);if(t)t.click();$("#sideMenu").classList.remove("open")});document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");["adminMedicinesTab","adminCustomersTab","adminOrdersTab"].forEach(id=>$("#"+id).hidden=true);$("#"+({adminMedicines:"adminMedicinesTab",adminCustomers:"adminCustomersTab",adminOrders:"adminOrdersTab"}[t.dataset.tab])).hidden=false;localStorage.setItem("zenoAdminTab",t.dataset.tab)});function restoreTab(){const t=localStorage.getItem("zenoAdminTab");if(t){const b=document.querySelector(`.tab[data-tab="${t}"]`);if(b)b.click()}}
