import { auth, db, firebaseConfig, customerEmailFromLogin } from "./firebase.js";
import { signInWithEmailAndPassword,onAuthStateChanged,signOut,createUserWithEmailAndPassword,getAuth,getIdTokenResult } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { collection,doc,getDoc,getDocs,addDoc,setDoc,updateDoc,deleteDoc,query,where,serverTimestamp,runTransaction,onSnapshot } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const $=s=>document.querySelector(s),money=n=>`₹${Number(n||0).toFixed(2)}`,esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
let medicines=[],customers=[],orders=[],bills=[],blacklistRequests=[],unsubscribeOrders=null;const customerApp=initializeApp(firebaseConfig,"zeno-customer-creator-v2"),customerAuth=getAuth(customerApp);
function notify(msg){
  const toast=$("#toast");
  if(toast){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2600)}
  showAdminNotification(msg);
}

async function showAdminNotification(msg){
  try{
    if(!('Notification' in window) || Notification.permission!=="granted") return;
    if(!('serviceWorker' in navigator)) return;
    const reg=await navigator.serviceWorker.ready;
    if(reg && reg.showNotification){
      await reg.showNotification("Zeno Life Care",{body:msg,icon:"./favicon.ico",badge:"./favicon.ico",tag:"zeno-admin"});
    }
  }catch(_){
    // Android Chrome does not allow `new Notification()` in many contexts.
    // Notification failure must never break order/status operations.
  }
}

async function registerNotificationServiceWorker(){
  try{
    if('serviceWorker' in navigator){
      await navigator.serviceWorker.register('./service-worker.js');
    }
  }catch(_){
    // Notifications are optional; the dashboard continues normally.
  }
}

async function requestNotifications(){
  if('Notification' in window && Notification.permission==="default"){
    try{await Notification.requestPermission()}catch{}
  }
}
if($("#adminLoginForm"))$("#adminLoginForm").addEventListener("submit",async e=>{e.preventDefault();$("#adminLoginMsg").textContent="Signing in…";try{const cred=await signInWithEmailAndPassword(auth,$("#adminEmail").value.trim(),$("#adminPassword").value);if(cred.user.email?.toLowerCase()!=="mrbituyr@gmail.com"){await signOut(auth);$("#adminLoginMsg").textContent="⚠ This is an Admin page. Only authorized Admin accounts can login here.";return}location.replace("admin-dashboard.html")}catch{$("#adminLoginMsg").textContent="⚠ This is an Admin page. Only authorized Admin accounts can login here, or the credentials are incorrect."}});
onAuthStateChanged(auth,async user=>{if(!user){if(location.pathname.endsWith("admin-dashboard.html"))location.replace("admin.html");return}if(location.pathname.endsWith("admin.html")){location.replace("admin-dashboard.html");return}try{if(user.email?.toLowerCase()!=="mrbituyr@gmail.com")throw 0;if($("#adminApp")){await registerNotificationServiceWorker();await requestNotifications();await loadAll();watchOrders();restoreTab()}}catch{await signOut(auth);location.replace("admin.html")}});
async function loadAll(){await Promise.all([loadMedicines(),loadCustomers(),loadOrders(),loadBills(),loadBlacklistRequests()]);stats();renderProfits()}
async function loadMedicines(){const s=await getDocs(collection(db,"medicines")),p=await getDocs(collection(db,"medicinePrivate")),pm=new Map(p.docs.map(d=>[d.id,d.data()]));medicines=s.docs.map(d=>({id:d.id,...d.data(),...(pm.get(d.id)||{})}));renderMedicines();renderStockReport()}
async function loadCustomers(){const s=await getDocs(collection(db,"customers"));customers=s.docs.map(d=>({id:d.id,...d.data()}));renderCustomers()}
async function loadBlacklistRequests(){try{const s=await getDocs(collection(db,"blacklistRequests"));blacklistRequests=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));renderBlacklistRequests()}catch{blacklistRequests=[];renderBlacklistRequests()}}
async function loadOrders(){const s=await getDocs(collection(db,"orders"));orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.orderTimeMs||0)-(a.orderTimeMs||0));renderOrders();stats()}
async function loadBills(){try{const s=await getDocs(collection(db,"bills"));bills=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdMs||0)-(a.createdMs||0));}catch{bills=[]}}
function watchOrders(){if(unsubscribeOrders)unsubscribeOrders();unsubscribeOrders=onSnapshot(query(collection(db,"orders")),snap=>{const prev=new Set(orders.map(o=>o.id));orders=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.orderTimeMs||0)-(a.orderTimeMs||0));const fresh=orders.filter(o=>!prev.has(o.id)&&o.status==="new");if(fresh.length)notify(`New order received • ${fresh[0].medicalName||fresh[0].customerName||"Customer"} • ${fresh[0].billId||"Bill"}`);renderOrders();stats()})}
function itemProfit(x){const m=medicines.find(v=>v.id===x.medicineId)||{};const rate=Number(x.rate||0),purchase=Number(x.purchaseRateAtOrder??m.purchaseRate??0),qty=Number(x.qty||0),gst=Number(m.gst||x.gstAtOrder||0),transport=Number(m.transport??x.transportAtOrder??0);const effectivePurchase=(purchase+gst+transport)*qty;return (rate*qty)-effectivePurchase}
function orderProfit(o){return (o.items||[]).reduce((sum,x)=>sum+itemProfit(x),0)}
function stats(){const low=medicines.filter(m=>Number(m.quantity)<=10),exp=medicines.filter(m=>{if(!m.expiry)return false;const d=new Date(m.expiry),n=new Date();return d>=new Date(n.getFullYear(),n.getMonth(),n.getDate())&&d<=new Date(n.getFullYear(),n.getMonth(),n.getDate()+30)}),profit=bills.reduce((s,b)=>s+Number(b.profit||0),0);$("#statMedicines").textContent=medicines.length;$("#statCustomers").textContent=customers.length;$("#statOrders").textContent=orders.filter(o=>o.status==="new").length;$("#statLow").textContent=low.length;$("#statExpiry").textContent=exp.length;$("#statProfit").textContent=money(profit);$("#alertPanel").innerHTML=(low.length||exp.length)?`<div class="alert-box">${low.length?`⚠️ ${low.length} low-stock medicine(s).`:""} ${exp.length?`⏳ ${exp.length} medicine(s) expiring within 30 days.`:""}</div>`:`<div class="alert-box success-alert">✓ Inventory looks healthy.</div>`}
function renderMedicines(){const term=($("#adminMedicineSearch")?.value||"").toLowerCase().trim(),list=medicines.filter(m=>(m.name||"").toLowerCase().includes(term)||(m.composition||"").toLowerCase().includes(term)||(m.category||"").toLowerCase().includes(term));$("#adminMedicineTable").innerHTML=`<div class="table-scroll"><table><thead><tr><th>Image</th><th>Drug</th><th>Qty</th><th>Expiry</th><th>MRP</th><th>N. Rate</th><th>Purchase</th><th>GST</th><th>Transport</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${list.map(m=>`<tr><td>${m.imageData?`<img class="table-thumb" src="${esc(m.imageData)}">`:"—"}</td><td><b>${esc(m.name)}</b><small>${esc(m.composition||"")}</small></td><td>${m.quantity}</td><td>${esc(m.expiry||"—")}</td><td>${money(m.mrp)}</td><td>${money(m.sellRate)}</td><td>${money(m.purchaseRate)}</td><td>${money(m.gst)}</td><td>${money(m.transport)}</td><td><button class="stock-toggle ${m.available?"yes":"no"}" data-stock="${m.id}">${m.available?"ON":"OFF"}</button></td><td><button class="mini" data-edit="${m.id}">Edit</button><button class="mini danger" data-del="${m.id}">Delete</button></td></tr>`).join("")}</tbody></table></div>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openMedicine(medicines.find(m=>m.id===b.dataset.edit)));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>deleteMedicine(b.dataset.del));document.querySelectorAll("[data-stock]").forEach(b=>b.onclick=()=>toggleStock(b.dataset.stock))}
function renderBlacklistRequests(){const box=$("#blacklistRequests");if(!box)return;const pending=blacklistRequests.filter(r=>r.status==="pending");box.innerHTML=pending.length?pending.map(r=>{const c=customers.find(x=>x.id===r.customerId);return `<div class="request-card glass"><div><b>${esc(c?.medicalName||r.loginId||"Customer")}</b><small>${esc(c?.name||"")} • ${esc(c?.phone||r.loginId||"")}</small></div><button class="mini primary" data-unblack-request="${r.id}" data-request-customer="${r.customerId}">Unblacklist & Approve</button></div>`}).join(""):"<div class='empty'>No pending blacklist requests.</div>";document.querySelectorAll("[data-unblack-request]").forEach(b=>b.onclick=()=>approveBlacklistRequest(b.dataset.unblackRequest,b.dataset.requestCustomer))}
async function approveBlacklistRequest(requestId,customerId){try{await updateDoc(doc(db,"customers",customerId),{active:true,updatedAt:serverTimestamp()});await updateDoc(doc(db,"blacklistRequests",requestId),{status:"approved",handledAt:serverTimestamp()});await Promise.all([loadCustomers(),loadBlacklistRequests()]);notify("Customer unblacklisted ✓")}catch(e){notify(e.message||"Could not approve request")}}
function renderCustomers(){const list=customers;$("#customerTable").innerHTML=`<div class="table-scroll"><table><thead><tr><th>Medical</th><th>Owner/Name</th><th>Phone</th><th>Address</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map(c=>`<tr class="${c.active===false?"blacklisted-row":""}"><td><b>${esc(c.medicalName||"")}</b><small>${esc(c.loginId||"")}</small></td><td>${esc(c.name||"")}</td><td>${esc(c.phone||"")}</td><td>${esc(c.address||"—")}</td><td>${c.active===false?`<span class="blacklisted-badge">⚠ BLACKLISTED</span>`:`<span class="status confirmed">Active</span>`}</td><td><button class="mini" data-cview="${c.id}">Details</button><button class="mini ${c.active===false?"primary":"danger"}" data-black="${c.id}">${c.active===false?"Unblacklist":"Blacklist"}</button></td></tr>`).join("")}</tbody></table></div>`;document.querySelectorAll("[data-black]").forEach(b=>b.onclick=()=>toggleCustomer(b.dataset.black));renderBlacklistRequests()}
function groupOrders(){const map=new Map();orders.forEach(o=>{const d=new Date(o.orderTimeMs||Date.now()).toLocaleDateString("en-IN");const key=d+"|"+(o.medicalName||o.customerName||"Customer");if(!map.has(key))map.set(key,{date:d,medical:o.medicalName||o.customerName||"Customer",orders:[]});map.get(key).orders.push(o)});return [...map.values()]}
function renderOrders(){const groups=groupOrders();$("#orderTable").innerHTML=groups.length?groups.map(g=>`<section class="order-day"><div class="day-head"><div><div class="eyebrow">${esc(g.date)}</div><h3>${esc(g.medical)}</h3></div><span>${g.orders.length} bill(s)</span></div>${g.orders.map(o=>`<article class="admin-order glass"><div><b>Bill ${esc(o.billId||o.id.slice(-6).toUpperCase())}</b><small>${new Date(o.orderTimeMs||Date.now()).toLocaleTimeString("en-IN")} • ${o.items?.length||0} products</small></div><strong>${money(o.total)}</strong><span class="status ${esc(o.status)}">${esc(o.status)}</span><button class="ghost" data-bill="${o.id}">Details</button><select data-status="${o.id}"><option value="new" ${o.status==="new"?"selected":""}>New</option><option value="confirmed" ${o.status==="confirmed"?"selected":""}>Confirm</option><option value="completed" ${o.status==="completed"?"selected":""}>Completed</option><option value="cancelled" ${o.status==="cancelled"?"selected":""}>Cancel</option></select></article>`).join("")}</section>`).join(""):"<div class='empty glass'>No orders yet.</div>";document.querySelectorAll("[data-bill]").forEach(b=>b.onclick=()=>openAdminBill(orders.find(o=>o.id===b.dataset.bill)));document.querySelectorAll("[data-status]").forEach(s=>s.onchange=()=>updateStatus(s.dataset.status,s.value))}
function billHtml(o){const totalProfit=orderProfit(o);return `<div class="bill"><div class="bill-head"><div><b>ZenoLife Care</b><small>Retailer Bill • Admin View</small></div><strong>${esc(o.billId||"")}</strong></div><div class="bill-customer"><b>${esc(o.medicalName||"")}</b><span>${esc(o.customerName||"")} • ${esc(o.phone||"")}</span>${o.address?`<span>${esc(o.address)}</span>`:""}</div><div class="bill-items">${(o.items||[]).map((x,i)=>{const m=medicines.find(v=>v.id===x.medicineId)||{};const purchase=Number(x.purchaseRateAtOrder??m.purchaseRate??0),gst=Number(m.gst??x.gstAtOrder??0),transport=Number(m.transport??x.transportAtOrder??0),profit=itemProfit(x);return `<div class="bill-line"><span>${i+1}. ${esc(x.name)} × ${x.qty}</span><span>N. Rate ${money(x.rate)} • Purchase ${money(purchase)} • GST ${money(gst)} • Transport ${money(transport)} • Profit ${money(profit)}</span></div>`}).join("")}</div><div class="bill-total"><span>Customer Total</span><b>${money(o.total)}</b></div><div class="admin-profit-box">Admin Profit <small>(N. Rate − (Purchase + GST + Transport))</small>: <b>${money(totalProfit)}</b></div><small>${new Date(o.orderTimeMs||Date.now()).toLocaleString("en-IN")} • ${esc(o.status)}</small></div>`}
function openAdminBill(o){if(!o)return;$("#adminBillContent").innerHTML=billHtml(o);$("#adminBillDialog").showModal()}
async function updateStatus(id,status){try{const ref=doc(db,"orders",id);if(status==="completed"){await runTransaction(db,async tx=>{const os=await tx.get(ref);if(!os.exists())throw Error("Order not found");const o=os.data();if(o.status!=="completed"){for(const x of o.items||[]){const mr=doc(db,"medicines",x.medicineId),ms=await tx.get(mr);if(ms.exists()){const n=Math.max(0,Number(ms.data().quantity||0)-Number(x.qty||0));tx.update(mr,{quantity:n,available:n>0,updatedAt:serverTimestamp()})}}}tx.update(ref,{status,updatedAt:serverTimestamp()})})}else await updateDoc(ref,{status,updatedAt:serverTimestamp()});await loadAll();notify(`Bill ${id.slice(-6).toUpperCase()} marked ${status}`)}catch(e){notify(e.message||"Status update failed")}}
async function toggleCustomer(id){const c=customers.find(x=>x.id===id);if(!c)return;const blacklist=c.active!==false;if(blacklist&&!confirm(`Blacklist ${c.medicalName||c.name}?`))return;await updateDoc(doc(db,"customers",id),{active:!blacklist,updatedAt:serverTimestamp()});renderCustomers();notify(blacklist?"Customer blacklisted ⚠":"Customer unblacklisted ✓")}
$("#customerForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const medicalName=$("#cMedical").value.trim(),name=$("#cName").value.trim(),phone=$("#cPhone").value.trim(),address=$("#cAddress").value.trim(),loginId=$("#cLogin").value.trim().toLowerCase(),password=$("#cPassword").value;if(!medicalName||!name||!phone||!address||!loginId||password.length<6)throw Error("Please fill all customer details.");const cred=await createUserWithEmailAndPassword(customerAuth,customerEmailFromLogin(loginId),password);await setDoc(doc(db,"customers",cred.user.uid),{medicalName,name,phone,address,loginId,active:true,createdAt:serverTimestamp()});await signOut(customerAuth);$("#customerDialog").close();await loadCustomers();stats();notify("Customer created ✓")}catch(e){try{await signOut(customerAuth)}catch{}$("#customerMsg").textContent=e.message||"Customer creation failed."}});
$("#medicineForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const id=$("#medicineId").value,imageFile=$("#mImage").files[0],data={name:$("#mName").value.trim(),category:$("#mCategory").value.trim(),composition:$("#mComposition").value.trim(),quantity:Number($("#mQty").value),expiry:$("#mExp").value,batchNo:$("#mBatch").value.trim(),unit:$("#mUnit").value.trim(),mrp:Number($("#mMrp").value),sellRate:Number($("#mSell").value),available:$("#mAvailable").checked,updatedAt:serverTimestamp()};if(imageFile)data.imageData=await compressImage(imageFile);let mid=id;if(mid)await updateDoc(doc(db,"medicines",mid),data);else mid=(await addDoc(collection(db,"medicines"),{...data,createdAt:serverTimestamp()})).id;await setDoc(doc(db,"medicinePrivate",mid),{purchaseRate:Number($("#mPurchase").value),gst:Number($("#mGst").value),transport:Number($("#mTransport").value),updatedAt:serverTimestamp()},{merge:true});$("#medicineDialog").close();await loadMedicines();stats();notify("Medicine saved ✓")}catch(e){$("#medicineMsg").textContent=e.message||"Save failed."}});
function openMedicine(m){$("#medicineForm").reset();$("#medicineId").value=m?.id||"";$("#medicineDialogTitle").textContent=m?"Edit Medicine":"Add Medicine";if(m){$("#mName").value=m.name||"";$("#mCategory").value=m.category||"";$("#mComposition").value=m.composition||"";$("#mQty").value=m.quantity??0;$("#mExp").value=m.expiry||"";$("#mBatch").value=m.batchNo||"";$("#mUnit").value=m.unit||"";$("#mMrp").value=m.mrp??0;$("#mSell").value=m.sellRate??0;$("#mPurchase").value=m.purchaseRate??0;$("#mGst").value=m.gst??0;$("#mTransport").value=m.transport??0;$("#mAvailable").checked=m.available!==false}$("#medicineDialog").showModal()}
async function deleteMedicine(id){if(!confirm("Delete this medicine?"))return;await deleteDoc(doc(db,"medicines",id));await deleteDoc(doc(db,"medicinePrivate",id));await loadMedicines();stats();notify("Medicine deleted")}
async function toggleStock(id){const m=medicines.find(x=>x.id===id);await updateDoc(doc(db,"medicines",id),{available:!m.available,updatedAt:serverTimestamp()});await loadMedicines()}
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const i=new Image();i.onload=()=>{const c=document.createElement("canvas"),s=Math.min(1,600/Math.max(i.width,i.height));c.width=i.width*s;c.height=i.height*s;c.getContext("2d").drawImage(i,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.68))};i.onerror=reject;i.src=r.result};r.readAsDataURL(file)})}

let manualBillItems=[],selectedReportIds=new Set();
function today(){return new Date().toISOString().slice(0,10)}
function nextBillNumber(){const n=Number(localStorage.getItem("zenoManualBillNo")||0)+1;localStorage.setItem("zenoManualBillNo",String(n));return `ZLC-${String(n).padStart(4,"0")}`}
function fillBillCustomers(){const s=$("#billCustomer");if(!s)return;s.innerHTML='<option value="">Walk-in / Manual Customer</option>'+customers.map(c=>`<option value="${esc(c.id)}">${esc(c.medicalName||c.name||"Customer")} — ${esc(c.phone||"")}</option>`).join("")}
function resetManualBill(){manualBillItems=[];$("#manualBillForm")?.reset();$("#billDate").value=today();fillBillCustomers();renderManualBill();renderBillSuggestions("")}
function selectBillCustomer(id){const c=customers.find(x=>x.id===id);if(!c)return;$("#billMedical").value=c.medicalName||"";$("#billCustomerName").value=c.name||"";$("#billPhone").value=c.phone||"";$("#billAddress").value=c.address||""}
function renderBillSuggestions(term){const q=(term||"").toLowerCase().trim();const list=medicines.filter(m=>{const n=(m.name||"").toLowerCase(),c=(m.composition||"").toLowerCase();return !q||n.startsWith(q)||n.includes(q)||c.includes(q)}).slice(0,18);$("#billDrugSuggestions").innerHTML=list.map(m=>`<button type="button" class="drug-suggestion" data-bill-add="${esc(m.id)}"><b>${esc(m.name)}</b><small>${esc(m.composition||"No composition")} • MRP ${money(m.mrp)} • N. Rate ${money(m.sellRate)}</small></button>`).join("")||'<div class="empty">No drug found.</div>';document.querySelectorAll("[data-bill-add]").forEach(b=>b.onclick=()=>addManualBillItem(b.dataset.billAdd))}
function addManualBillItem(id){const m=medicines.find(x=>x.id===id);if(!m)return;const found=manualBillItems.find(x=>x.medicineId===id);if(found)found.qty+=1;else manualBillItems.push({medicineId:id,name:m.name,qty:1,rate:Number(m.sellRate||0),mrp:Number(m.mrp||0),batchNo:m.batchNo||"",expiry:m.expiry||"",unit:m.unit||"",purchaseRateAtOrder:Number(m.purchaseRate||0),gstAtOrder:Number(m.gst||0),transportAtOrder:Number(m.transport||0)});renderManualBill();$("#billDrugSearch").focus()}
function renderManualBill(){const box=$("#manualBillLines");if(!box)return;box.innerHTML=manualBillItems.length?manualBillItems.map((x,i)=>`<div class="bill-editor-row"><div><b>${i+1}. ${esc(x.name)}</b><small>${esc(x.unit||"")} • Batch ${esc(x.batchNo||"—")} • Exp ${esc(x.expiry||"—")} • MRP ${money(x.mrp)}</small></div><input class="bill-qty" data-bqty="${i}" type="number" min="1" value="${x.qty}"><b>${money(x.rate*x.qty)}</b><button type="button" class="mini danger" data-bremove="${i}">×</button></div>`).join(""):'<div class="empty">Drug search karke medicine add karo.</div>';manualBillItems.forEach((x,i)=>{const q=document.querySelector(`[data-bqty="${i}"]`);if(q)q.oninput=()=>{x.qty=Math.max(1,Number(q.value||1));renderManualBill()}});document.querySelectorAll("[data-bremove]").forEach(b=>b.onclick=()=>{manualBillItems.splice(Number(b.dataset.bremove),1);renderManualBill()});$("#manualBillTotal").textContent=money(manualBillItems.reduce((a,x)=>a+x.qty*x.rate,0))}
function retailerInfo(){return JSON.parse(localStorage.getItem("zenoRetailerInfo")||'{"name":"ZenoLife Care","phone":"","address":""}')}
function billPrintableHtml(o){const r=retailerInfo();return `<div class="print-bill"><div class="print-head"><div><h1>${esc(r.name||"ZenoLife Care")}</h1><p>${esc(r.phone||"")} ${r.address?"• "+esc(r.address):""}</p></div><div class="bill-no"><b>INVOICE</b><strong>${esc(o.billId||"")}</strong><small>${esc(o.billDate||"")}</small></div></div><div class="party"><div><small>BILL TO</small><b>${esc(o.medicalName||"Walk-in Customer")}</b><span>${esc(o.customerName||"")}</span><span>${esc(o.phone||"")}</span><span>${esc(o.address||"")}</span></div></div><table class="print-table"><thead><tr><th><input type="checkbox" id="selectAllReport"></th><th>S.No</th><th>Drug Name</th><th>Unit</th><th>Batch No.</th><th>Exp.</th><th>MRP</th><th>N. Rate</th><th>Qty</th><th>Amount</th></tr></thead><tbody>${(o.items||[]).map((x,i)=>`<tr><td>${i+1}</td><td><b>${esc(x.name)}</b>${x.composition?`<small>${esc(x.composition)}</small>`:""}</td><td>${esc(x.unit||"—")}</td><td>${esc(x.batchNo||"—")}</td><td>${esc(x.expiry||"—")}</td><td>${money(x.mrp)}</td><td>${money(x.rate)}</td><td>${x.qty}</td><td>${money(x.lineTotal)}</td></tr>`).join("")}</tbody></table><div class="print-total"><span>Total Amount</span><b>${money(o.total)}</b></div><p class="print-note">Thank you for your business.</p></div>`}
async function saveManualBill(){const items=manualBillItems.map(x=>({...x,lineTotal:x.qty*x.rate,composition:(medicines.find(m=>m.id===x.medicineId)||{}).composition||""}));if(!items.length)return $("#manualBillMsg").textContent="At least one drug add karo.";const billId=nextBillNumber(),billDate=$("#billDate").value||today(),profit=items.reduce((sum,x)=>sum+itemProfit(x),0),o={billId,billDate,customerId:$("#billCustomer").value||"manual",customerName:$("#billCustomerName").value.trim(),medicalName:$("#billMedical").value.trim()||"Walk-in Customer",phone:$("#billPhone").value.trim(),address:$("#billAddress").value.trim(),items,total:items.reduce((a,x)=>a+x.lineTotal,0),profit,status:"completed",manual:true,createdMs:Date.now(),createdAt:serverTimestamp()};try{await runTransaction(db,async tx=>{for(const x of items){const ref=doc(db,"medicines",x.medicineId),snap=await tx.get(ref);if(snap.exists()){const cur=Number(snap.data().quantity||0),next=Math.max(0,cur-Number(x.qty||0));tx.update(ref,{quantity:next,available:next>0,updatedAt:serverTimestamp()})}}const ref=doc(collection(db,"bills"));tx.set(ref,o)});bills=[o,...bills];$("#manualBillMsg").textContent=`${billId} completed ✓`;stats();renderProfits();await loadMedicines();openBillPrint(o);resetManualBill()}catch(e){$("#manualBillMsg").textContent=e.message||"Bill save failed."}}
function openBillPrint(o){const w=window.open("","_blank");if(!w){notify("Browser popup blocked. Allow popups for PDF/print.");return}w.document.write(`<!doctype html><html><head><title>${esc(o.billId)}</title><style>body{font-family:Arial,sans-serif;margin:0;padding:28px;color:#222}.print-bill{max-width:1000px;margin:auto}.print-head{display:flex;justify-content:space-between;border-bottom:2px solid #222;padding-bottom:15px}.print-head h1{margin:0 0 5px}.print-head p{margin:0;color:#666}.bill-no{text-align:right}.bill-no>*{display:block}.party{padding:18px 0}.party small,.party span{display:block;color:#666;margin-top:4px}.print-table{width:100%;border-collapse:collapse;font-size:12px}.print-table th,.print-table td{border:1px solid #ccc;padding:8px;text-align:left}.print-table th{background:#f6eef3}.print-table td small{display:block;color:#777}.print-total{display:flex;justify-content:flex-end;gap:30px;font-size:18px;padding:18px 0;border-bottom:1px solid #ddd}.print-note{text-align:center;color:#777}@media print{body{padding:0}.print-table th{background:#eee!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body>${billPrintableHtml(o)}<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
function renderStockReport(){const q=($("#stockReportSearch")?.value||"").toLowerCase().trim(),list=medicines.filter(m=>(m.name||"").toLowerCase().includes(q)||(m.composition||"").toLowerCase().includes(q)||(m.batchNo||"").toLowerCase().includes(q));$("#stockReport").innerHTML=`<div class="table-scroll"><table><thead><tr><th><input type="checkbox" id="selectAllReport"></th><th>S.No</th><th>Drug Name</th><th>Salt / Composition</th><th>MRP</th><th>N. Rate</th><th>Expiry</th><th>Batch No.</th><th>Unit</th><th>Qty</th></tr></thead><tbody>${list.map((m,i)=>`<tr><td><input type="checkbox" class="report-check" data-report-id="${esc(m.id)}" ${selectedReportIds.has(m.id)?"checked":""}></td><td>${i+1}</td><td><b>${esc(m.name)}</b></td><td>${esc(m.composition||"—")}</td><td>${money(m.mrp)}</td><td>${money(m.sellRate)}</td><td>${esc(m.expiry||"—")}</td><td>${esc(m.batchNo||"—")}</td><td>${esc(m.unit||"—")}</td><td>${m.quantity??0}</td></tr>`).join("")}</tbody></table></div>`};document.querySelectorAll(".report-check").forEach(c=>c.onchange=()=>{c.checked?selectedReportIds.add(c.dataset.reportId):selectedReportIds.delete(c.dataset.reportId)});const all=$("#selectAllReport");if(all)all.onchange=()=>{document.querySelectorAll(".report-check").forEach(c=>{c.checked=all.checked;c.checked?selectedReportIds.add(c.dataset.reportId):selectedReportIds.delete(c.dataset.reportId)})}}
function openStockPrint(){const filtered=medicines.filter(m=>{const q=($("#stockReportSearch")?.value||"").toLowerCase().trim();return !q||(m.name||"").toLowerCase().includes(q)||(m.composition||"").toLowerCase().includes(q)||(m.batchNo||"").toLowerCase().includes(q)});const rows=selectedReportIds.size?filtered.filter(m=>selectedReportIds.has(m.id)):filtered;const r=retailerInfo();const w=window.open("","_blank");if(!w)return;w.document.write(`<!doctype html><html><head><title>Zeno Drug Details</title><style>body{font-family:Arial;margin:25px;color:#222}h1{margin-bottom:4px}.sub{color:#666;margin-bottom:20px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #bbb;padding:7px}th{background:#f4edf2}</style></head><body><h1>${esc(r.name||"ZenoLife Care")} — Drug Details</h1><div class="sub">${esc(r.phone||"")} ${esc(r.address||"")}</div><table><thead><tr><th>S.No</th><th>Drug Name</th><th>Salt</th><th>MRP</th><th>N. Rate</th><th>Exp</th><th>Batch No.</th><th>Unit</th><th>Qty</th></tr></thead><tbody>${rows.map((m,i)=>`<tr><td>${i+1}</td><td>${esc(m.name)}</td><td>${esc(m.composition||"")}</td><td>${money(m.mrp)}</td><td>${money(m.sellRate)}</td><td>${esc(m.expiry||"")}</td><td>${esc(m.batchNo||"")}</td><td>${esc(m.unit||"")}</td><td>${m.quantity??0}</td></tr>`).join("")}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}

function renderProfits(){const box=$("#profitTable");if(!box)return;const d=$("#profitDate")?.value||today(),list=bills.filter(b=>(b.billDate||"").slice(0,10)===d),sales=list.reduce((a,b)=>a+Number(b.total||0),0),profit=list.reduce((a,b)=>a+Number(b.profit||0),0);$("#profitDaySales").textContent=money(sales);$("#profitDayTotal").textContent=money(profit);box.innerHTML=list.length?`<div class="table-scroll"><table><thead><tr><th>S.No</th><th>Bill No.</th><th>Customer</th><th>Bill Amount</th><th>Profit</th><th>Date</th></tr></thead><tbody>${list.map((b,i)=>`<tr><td>${i+1}</td><td><b>${esc(b.billId)}</b></td><td>${esc(b.medicalName||b.customerName||"Walk-in")}</td><td>${money(b.total)}</td><td><b>${money(b.profit)}</b></td><td>${esc(b.billDate||"")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">Is date par koi completed manual bill nahi hai.</div>`}
function loadRetailerInfo(){const r=retailerInfo();if($("#rName")){$("#rName").value=r.name||"ZenoLife Care";$("#rPhone").value=r.phone||"";$("#rAddress").value=r.address||""}}
$("#businessProfileBtn")?.addEventListener("click",()=>{loadRetailerInfo();$("#businessProfileDialog").showModal()});$("#closeBusinessProfile")?.addEventListener("click",()=>$("#businessProfileDialog").close());$("#businessProfileForm")?.addEventListener("submit",e=>{e.preventDefault();localStorage.setItem("zenoRetailerInfo",JSON.stringify({name:$("#rName").value.trim(),phone:$("#rPhone").value.trim(),address:$("#rAddress").value.trim()}));$("#businessProfileMsg").textContent="Saved ✓";setTimeout(()=>$("#businessProfileDialog").close(),500)});
$("#newManualBill")?.addEventListener("click",()=>{resetManualBill();$("#manualBillDialog").showModal()});$("#closeManualBill")?.addEventListener("click",()=>$("#manualBillDialog").close());$("#billCustomer")?.addEventListener("change",e=>selectBillCustomer(e.target.value));$("#billDrugSearch")?.addEventListener("input",e=>renderBillSuggestions(e.target.value));$("#saveManualBill")?.addEventListener("click",saveManualBill);$("#previewManualBill")?.addEventListener("click",()=>{const items=manualBillItems.map(x=>({...x,lineTotal:x.qty*x.rate,composition:(medicines.find(m=>m.id===x.medicineId)||{}).composition||""}));if(!items.length)return notify("Drug add karo pehle");openBillPrint({billId:"PREVIEW",billDate:$("#billDate").value||today(),medicalName:$("#billMedical").value||"Walk-in Customer",customerName:$("#billCustomerName").value,phone:$("#billPhone").value,address:$("#billAddress").value,items,total:items.reduce((a,x)=>a+x.lineTotal,0)})});$("#stockReportSearch")?.addEventListener("input",renderStockReport);$("#clearStockReport")?.addEventListener("click",()=>{$("#stockReportSearch").value="";renderStockReport()});$("#printStockReport")?.addEventListener("click",openStockPrint);$("#profitDate")?.addEventListener("change",renderProfits);$("#profitToday")?.addEventListener("click",()=>{$("#profitDate").value=today();renderProfits()});
$("#adminMedicineSearch")?.addEventListener("input",renderMedicines);$("#clearAdminSearch")?.addEventListener("click",()=>{$("#adminMedicineSearch").value="";renderMedicines()});$("#addMedicineBtn")?.addEventListener("click",()=>openMedicine());$("#closeMedicine")?.addEventListener("click",()=>$("#medicineDialog").close());$("#addCustomerBtn")?.addEventListener("click",()=>{$("#customerForm").reset();$("#customerDialog").showModal()});$("#closeCustomer")?.addEventListener("click",()=>$("#customerDialog").close());$("#adminLogout")?.addEventListener("click",async()=>{await signOut(auth);location.replace("admin.html")});$("#supportBtn")?.addEventListener("click",()=>$("#supportDialog").showModal());$("#closeSupport")?.addEventListener("click",()=>$("#supportDialog").close());$("#closeAdminBill")?.addEventListener("click",()=>$("#adminBillDialog").close());$("#menuBtn")?.addEventListener("click",()=>$("#sideMenu").classList.add("open"));$("#closeMenu")?.addEventListener("click",()=>$("#sideMenu").classList.remove("open"));document.querySelectorAll("[data-menu-tab]").forEach(b=>b.onclick=()=>{const t=document.querySelector(`.tab[data-tab="${b.dataset.menuTab}"]`);if(t)t.click();$("#sideMenu").classList.remove("open")});document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");["adminMedicinesTab","adminCustomersTab","adminOrdersTab","adminBillingTab","adminStockReportTab","adminProfitsTab"].forEach(id=>$("#"+id).hidden=true);$("#"+({adminMedicines:"adminMedicinesTab",adminCustomers:"adminCustomersTab",adminOrders:"adminOrdersTab",adminBilling:"adminBillingTab",adminStockReport:"adminStockReportTab",adminProfits:"adminProfitsTab"}[t.dataset.tab])).hidden=false;localStorage.setItem("zenoAdminTab",t.dataset.tab)});function restoreTab(){const t=localStorage.getItem("zenoAdminTab");if(t){const b=document.querySelector(`.tab[data-tab="${t}"]`);if(b)b.click()}}
