import { auth, db } from "./firebase.js";
import { onAuthStateChanged, signOut, updatePassword, EmailAuthProvider, reauthenticateWithCredential } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { collection, doc, getDoc, getDocs, query, where, serverTimestamp, writeBatch, deleteDoc } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const $=s=>document.querySelector(s), money=n=>`₹${Number(n||0).toFixed(2)}`;
let currentUser=null,customer=null,medicines=[],orders=[];
let cart=JSON.parse(localStorage.getItem("zenoCart")||"[]"),toastTimer;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const medicineName=m=>m.name||m.drugName||m.medicineName||"Medicine";
const sellRate=m=>Number(m.sellRate??m.nRate??m.rate??m.netRate??0);
const expiry=m=>m.expiry||m.expiryDate||"—";
const mrp=m=>{const v=m.mrp??m.MRP??m.maximumRetailPrice;return v==null||v===""?"—":money(v)};
const qty=m=>m.quantity??m.stock??"—";
const orderDate=o=>o.createdAt?.toDate?.()||(o.orderTimeMs?new Date(o.orderTimeMs):null);
function toast(msg){if(!$("#toast"))return;$("#toast").textContent=msg;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2800)}
function showOrderAnimation(){const el=$("#orderSuccess");if(!el)return;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}

onAuthStateChanged(auth,async user=>{
 if(!user){location.replace("index.html");return} currentUser=user;
 try{const s=await getDoc(doc(db,"customers",user.uid)); if(!s.exists()){await signOut(auth);location.replace("index.html");return}
  customer=s.data();
  if(customer.active===false){location.replace("index.html#blacklisted");return}
  $("#customerName").textContent=customer.name||"Customer";$("#medicalName").textContent=customer.medicalName||"Customer Portal";
  $("#welcome").textContent=`Hello, ${(customer.name||"Customer").split(" ")[0]} ✿`;
  $("#profileMedical").textContent=customer.medicalName||"";$("#profilePhone").textContent=customer.phone||"";$("#profileAddress").textContent=customer.address||"Address not added";
  await Promise.all([loadMedicines(),loadOrders()]);renderCart();restoreTab();
 }catch(e){console.error(e);toast("Data load nahi ho pa raha. Firebase Rules check karo.")}
});

async function loadMedicines(){try{const s=await getDocs(collection(db,"medicines"));medicines=s.docs.map(d=>({id:d.id,...d.data()})).filter(m=>medicineName(m)!=="Medicine").sort((a,b)=>medicineName(a).localeCompare(medicineName(b)));renderChips();renderMedicines()}catch(e){console.error(e);$("#medicineGrid").innerHTML=`<div class="empty glass">Medicine list load nahi hui.</div>`}}
function renderChips(){const cats=[...new Set(medicines.map(m=>m.category).filter(Boolean))];$("#categoryChips").innerHTML=cats.length?`<button class="chip active" data-cat="">All</button>`+cats.map(c=>`<button class="chip" data-cat="${esc(c)}">${esc(c)}</button>`).join(""):"";document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-cat]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderMedicines()})}
function renderMedicines(){const term=($("#search")?.value||"").toLowerCase().trim(),cat=document.querySelector("[data-cat].active")?.dataset.cat||"",list=medicines.filter(m=>(!cat||m.category===cat)&&(medicineName(m).toLowerCase().includes(term)||String(m.composition||"").toLowerCase().includes(term)));
 $("#medicineGrid").innerHTML=list.map(m=>{const available=m.available!==false&&Number(m.quantity??m.stock??0)>0,img=m.imageData||m.imageUrl||m.image||"";return `<article class="medicine-card glass"><div class="stock-dot ${available?"on":"off"}"></div>${img?`<img class="medicine-image small-product" src="${esc(img)}" alt="${esc(medicineName(m))}">`:`<div class="medicine-image small-product placeholder">✿</div>`}<div class="med-top"><span class="med-icon">✿</span><span class="stock-label">${available?"Available":"Not available"}</span></div><h3>${esc(medicineName(m))}</h3>${m.composition?`<div class="composition-mini">${esc(m.composition)}</div>`:""}<div class="rate-row"><span>N. Rate</span><b>${money(sellRate(m))}</b></div><div class="rate-row"><span>Exp.</span><b>${esc(expiry(m))}</b></div><div class="rate-row"><span>MRP</span><b>${mrp(m)}</b></div><div class="card-actions"><button class="ghost" data-details="${esc(m.id)}">Details</button><button class="primary" data-add="${esc(m.id)}" ${available?"":"disabled"}>Add to Cart</button></div></article>`}).join("");$("#emptyMedicines").hidden=!!list.length;document.querySelectorAll("[data-details]").forEach(b=>b.onclick=()=>location.href=`drug-details.html?id=${encodeURIComponent(b.dataset.details)}`);document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function addToCart(id){const m=medicines.find(x=>x.id===id),max=Number(m?.quantity??m?.stock??0);if(!m||m.available===false||max<1)return;const x=cart.find(a=>a.id===id);if(x)x.qty=Math.min(max,x.qty+1);else cart.push({id,qty:1});renderCart();toast(`${medicineName(m)} cart me add ho gayi ✓`)}
function changeQty(id,d){const x=cart.find(a=>a.id===id),m=medicines.find(a=>a.id===id);if(!x||!m)return;const max=Number(m.quantity??m.stock??0);x.qty=Math.max(0,Math.min(max,x.qty+d));if(!x.qty)cart=cart.filter(a=>a.id!==id);renderCart()}
function items(){return cart.map(x=>({...x,m:medicines.find(a=>a.id===x.id)})).filter(x=>x.m)}
function renderCart(){localStorage.setItem("zenoCart",JSON.stringify(cart));$("#cartCount").textContent=cart.reduce((s,x)=>s+x.qty,0);const its=items(),sub=its.reduce((s,x)=>s+sellRate(x.m)*x.qty,0);$("#cartList").innerHTML=its.length?its.map(x=>`<div class="cart-item"><div><b>${esc(medicineName(x.m))}</b><small>${money(sellRate(x.m))} × ${x.qty}</small></div><div class="qty-control"><button data-minus="${x.id}">−</button><b>${x.qty}</b><button data-plus="${x.id}">+</button><button class="mini danger" data-remove="${x.id}">×</button></div></div>`).join(""):"<div class='empty'>Cart is empty.</div>";$("#cartSubtotal").textContent=money(sub);$("#cartTotal").textContent=money(sub);$("#cartDiscount").textContent="₹0.00";$("#placeCartOrder").disabled=!its.length;document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==b.dataset.remove);renderCart()})}

async function loadOrders(){try{const s=await getDocs(query(collection(db,"orders"),where("customerId","==",currentUser.uid)));orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(orderDate(b)?.getTime()||0)-(orderDate(a)?.getTime()||0));renderOrders()}catch(e){console.error(e);orders=[];renderOrders()}}
function renderOrders(){const groups=new Map();orders.forEach(o=>{const d=orderDate(o)?.toLocaleDateString("en-IN")||"Unknown date";if(!groups.has(d))groups.set(d,[]);groups.get(d).push(o)});$("#ordersList").innerHTML=orders.length?[...groups].map(([date,list])=>`<div class="day-group"><h3>📅 ${date}</h3>${list.map(o=>`<article class="order-card glass"><div><b>Bill ${esc(o.billId||o.id.slice(-6).toUpperCase())}</b><small>${esc(o.medicalName||customer.medicalName||"")} • ${o.items?.length||1} item(s)</small></div><div><b>${money(o.total||0)}</b><small>${esc(o.status||"new")}</small></div><button class="ghost" data-view-order="${o.id}">Details</button>${o.status==="new"||o.status==="confirmed"?`<button class="mini danger" data-cancel="${o.id}">Cancel</button>`:""}<button class="mini danger" data-delete-order="${o.id}">Clear</button></article>`).join("")}</div>`).join(""):"<div class='empty glass'>No old orders.</div>";document.querySelectorAll("[data-view-order]").forEach(b=>b.onclick=()=>openBill(orders.find(o=>o.id===b.dataset.viewOrder),false));document.querySelectorAll("[data-cancel]").forEach(b=>b.onclick=()=>cancelOrder(b.dataset.cancel));document.querySelectorAll("[data-delete-order]").forEach(b=>b.onclick=()=>deleteOrder(b.dataset.deleteOrder))}
function billHtml(o,admin=false){return `<div class="bill"><div class="bill-head"><div><b>ZenoLife Care</b><small>Medical Bill</small></div><strong>${esc(o.billId||o.id.slice(-6).toUpperCase())}</strong></div><div class="bill-customer"><b>${esc(o.medicalName||"")}</b><span>${esc(o.customerName||"")} • ${esc(o.phone||"")}</span>${o.address?`<span>${esc(o.address)}</span>`:""}</div><div class="bill-items">${(o.items||[]).map((x,i)=>`<div class="bill-line"><span><b>${i+1}. ${esc(x.name)}</b><small>${esc(x.composition||"")} • Unit ${esc(x.unit||"—")} • Batch ${esc(x.batchNo||"—")} • Exp ${esc(x.expiry||"—")} • MRP ${money(x.mrp)}</small></span><span>${x.qty} × ${money(x.rate)} = <b>${money(x.lineTotal)}</b></span></div>`).join("")}</div><div class="bill-total"><span>Total Amount</span><b>${money(o.total)}</b></div><small>${orderDate(o)?.toLocaleString("en-IN")||""} • ${esc(o.status||"")}</small></div>`}
function openBill(o,admin=false){if(!o)return;$("#billContent").innerHTML=billHtml(o,admin);$("#billDialog").showModal()}
async function cancelOrder(id){if(!confirm("Cancel this order?"))return;try{await import("https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js").then(({updateDoc})=>updateDoc(doc(db,"orders",id),{status:"cancelled",updatedAt:serverTimestamp()}));toast("Order cancelled ✓");loadOrders()}catch(e){toast(e.message||"Cancel failed")}}
async function deleteOrder(id){if(!confirm("Clear this old order from your history?"))return;try{await deleteDoc(doc(db,"orders",id));orders=orders.filter(o=>o.id!==id);renderOrders();toast("Order history cleared ✓")}catch(e){toast(e.message||"Could not clear order")}}

$("#placeCartOrder").onclick=async()=>{const its=items();if(!its.length)return;const total=its.reduce((s,x)=>s+sellRate(x.m)*x.qty,0);$("#cartMsg").textContent="Creating your bill…";try{const now=Date.now(),billId=`ZLC-${now.toString(36).toUpperCase()}`;const batch=writeBatch(db),ref=doc(collection(db,"orders"));batch.set(ref,{billId,customerId:currentUser.uid,customerName:customer.name||"",medicalName:customer.medicalName||"",phone:customer.phone||"",address:customer.address||"",items:its.map(x=>({medicineId:x.m.id,name:medicineName(x.m),composition:x.m.composition||"",unit:x.m.unit||"",batchNo:x.m.batchNo||"",expiry:expiry(x.m),qty:x.qty,rate:sellRate(x.m),mrp:Number(x.m.mrp??0),lineTotal:sellRate(x.m)*x.qty,purchaseRateAtOrder:Number(x.m.purchaseRate||0)})),total,status:"new",createdAt:serverTimestamp(),orderTimeMs:now});await batch.commit();cart=[];renderCart();await loadOrders();$("#cartDialog").close();showOrderAnimation();toast(`Order ${billId} sent ✓`)}catch(e){console.error(e);$("#cartMsg").textContent=e.message||"Order failed"}};

$("#search").oninput=renderMedicines;$("#clearSearch").onclick=()=>{$("#search").value="";renderMedicines()};$("#refreshBtn").onclick=async()=>{await Promise.all([loadMedicines(),loadOrders()]);toast("Updated ✓")};async function logout(){await signOut(auth);localStorage.removeItem("zenoCustomerTab");location.replace("index.html")}
$("#logoutBtn").onclick=logout;$("#menuLogout")?.addEventListener("click",logout);$("#menuSupport")?.addEventListener("click",()=>{$("#sideMenu").classList.remove("open");$("#supportDialog").showModal()});$("#clearAllHistory")?.addEventListener("click",async()=>{if(!orders.length||!confirm("Clear all your old order history?"))return;try{await Promise.all(orders.map(o=>deleteDoc(doc(db,"orders",o.id))));orders=[];renderOrders();toast("All old history cleared ✓")}catch(e){toast(e.message||"Could not clear history")}});$("#supportBtn").onclick=()=>$("#supportDialog").showModal();$("#closeSupport").onclick=()=>$("#supportDialog").close();$("#cartBtn").onclick=()=>$("#cartDialog").showModal();$("#closeCart").onclick=()=>$("#cartDialog").close();$("#closeBill").onclick=()=>$("#billDialog").close();$("#profileBtn").onclick=()=>$("#profileDialog").showModal();$("#closeProfile").onclick=()=>$("#profileDialog").close();$("#menuBtn").onclick=()=>$("#sideMenu").classList.add("open");$("#closeMenu").onclick=()=>$("#sideMenu").classList.remove("open");document.querySelectorAll("[data-menu-tab]").forEach(b=>b.onclick=()=>{const t=b.dataset.menuTab,tab=document.querySelector(`.tab[data-tab="${t}"]`);if(tab)tab.click();$("#sideMenu").classList.remove("open")});$("#profileForm").addEventListener("submit",async e=>{e.preventDefault();try{const oldp=$("#currentPassword").value,newp=$("#newPassword").value;await reauthenticateWithCredential(currentUser,EmailAuthProvider.credential(currentUser.email,oldp));await updatePassword(currentUser,newp);$("#profileMsg").textContent="Password updated ✓"}catch{ $("#profileMsg").textContent="Password update failed."}});document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");const o=t.dataset.tab==="orders";$("#medicinesTab").hidden=o;$("#ordersTab").hidden=!o;localStorage.setItem("zenoCustomerTab",t.dataset.tab)});function restoreTab(){const t=localStorage.getItem("zenoCustomerTab");if(t){const b=document.querySelector(`.tab[data-tab="${t}"]`);if(b)b.click()}}
